DirectoryPath: overrides
IgnoreURLs:
  - linkedin.com/in
  - twitter.com
  - fonts.gstatic.com
IgnoreDirectoryMissingTrailingSlash: true
IgonreAltMissing: true
IgnoreSSLVerify: true
IgonoreDirs:
  - macros
IgnoreInternalEmptyHash: true
ExternalTimeout: 60
HTTPHeaders:
  "Range": "bytes=0-10"
  "Accept": "*/*"