site_name: danielcristho
site_author: Daniel Pepuho
site_description: >-
  My tech documentation.
copyright: > # should remain a link to the original theme
  &copy; 2023 Daniel Pepuho
theme:
    name: material
    features:
    # - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    # - navigation.tabs.sticky # tabs always show
    # - navigation.sections # sections are rendered as groups in the sidebar
    # - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    # - toc.integrate # show table of contents to navigation panel
    # - header.autohide
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button
    - content.code.annotate
    font:
      text: Noto Serif
      code: Roboto Mono
    palette:
      primary: white
      accent: deep orange
    icon:
      logo: fontawesome/solid/terminal
      repo: fontawesome/brands/github
      edit: material/file-edit-outline
    favicon: assets/images/icon.svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danielcristho
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chrstdan
  disqus: "danielcristho-github-io"
extra_css:
    - assets/extra.css
extra_javascript:
    - assets/extra.js
