site_name: danielcristho
site_author: Daniel Pepuho
site_description: >-
  My tech documentation.

# Repository
repo_name: danielcristho/tech-docs
repo_url: https://github.com/danielcristho/tech-docs
site_url: "https://tech-docs-swart.vercel.app"
# edit_uri: "edit/master/blog/"

docs_dir: docs
theme:
  name: material
  custom_dir: overrides

  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: assets/images/icon.svg


  font:
    text: Enriqueta
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - primary: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
      - navigation.top
      - navigation.instant
      - navigation.tabs
      - search.suggest
      - content.code.annotate
      - toc.follow
      - content.tooltips
      - navigation.indexes
      - content.code.copy

    # 404 page
  static_templates:
    - 404.html

    # Stylesheet
  extra_css:
    - stylesheets/extra.css

  language: en

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Plugins
plugins:
  - meta-descriptions
  - macros:
      j2_block_start_string: "[[[%"
      j2_block_end_string: "%]]]"
      j2_variable_start_string: "[[["
      j2_variable_end_string: "]]]"
      include_yaml:
        - macros/data.yml
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      archive: false
      categories: false
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\-\_]'
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
  - rss:
      match_path: posts/.*
      abstract_chars_count: 5000
      date_from_meta:
        as_creation: date
      categories:
        - tags
      comments_path: "#__comments"

# Customization
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Docs: index.md
  - Tags: tags.md
  - Connect: social.md