site_name: danielcristho
site_author: Daniel Pepuho
site_description: >-
  My tech documentation.

# Repository
repo_name: danielcristho/tech-docs
repo_url: https://github.com/danielcristho/tech-docs
site_url: "http://danielcristho.me"
# edit_uri: "edit/master/blog/"

docs_dir: docs
theme:
  name: material

  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: assets/images/icon.svg


  font:
    text: Enriqueta
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - primary: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
      - navigation.top
      - navigation.instant
      - navigation.tabs
      - search.suggest
      - content.code.annotate
      - toc.follow
      - content.tooltips
      - navigation.indexes

  language: en

  # 404 page
  static_templates:
    - 404.html

nav:
  - Docs:
      - index.md
